### ISSUE TITLE
Use kubernetes secret vs bare env var

### ISSUE THREAD

**Issue by jasonkeene** [DataDog/pks-k8s-setup#1]
You can populate environment variables via kubernetes secrets. Something like:

```
    env:
      - name: DD_API_KEY
        valueFrom:
          secretKeyRef:
            name: datadog
            key: api-key
```
